// Code generated by schema-generate. DO NOT EDIT.

package plan

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
)

// Check
type Check struct {
	Command           string  `json:"command"`
	ExpectedExitCodes []int64 `json:"expected_exit_codes"`
	Id                string  `json:"id"`
}

// DoStep
type DoStep struct {
	Id   string `json:"id"`
	Text string `json:"text"`
}

// PlanOutput
type PlanOutput struct {
	AcceptanceCriteria []PlannedAcceptanceCriterion `json:"acceptance_criteria"`
	DoSteps            []DoStep                     `json:"do_steps"`
}

// PlanResponse
type PlanResponse struct {
	PlanOutput *PlanOutput `json:"plan_output"`
	Status     string      `json:"status"`
	StopReason string      `json:"stop_reason,omitempty"`
	Summary    string      `json:"summary"`
}

// PlannedAcceptanceCriterion
type PlannedAcceptanceCriterion struct {
	Checks []Check `json:"checks"`
	Id     string  `json:"id"`
	Text   string  `json:"text"`
}

func (strct *Check) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
	comma := false
	// "Command" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "command" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"command\": ")
	if tmp, err := json.Marshal(strct.Command); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "ExpectedExitCodes" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "expected_exit_codes" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"expected_exit_codes\": ")
	if tmp, err := json.Marshal(strct.ExpectedExitCodes); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Id" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "id" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"id\": ")
	if tmp, err := json.Marshal(strct.Id); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Check) UnmarshalJSON(b []byte) error {
	commandReceived := false
	expected_exit_codesReceived := false
	idReceived := false
	var jsonMap map[string]json.RawMessage
	if err := json.Unmarshal(b, &jsonMap); err != nil {
		return err
	}
	// parse all the defined properties
	for k, v := range jsonMap {
		switch k {
		case "command":
			if err := json.Unmarshal([]byte(v), &strct.Command); err != nil {
				return err
			}
			commandReceived = true
		case "expected_exit_codes":
			if err := json.Unmarshal([]byte(v), &strct.ExpectedExitCodes); err != nil {
				return err
			}
			expected_exit_codesReceived = true
		case "id":
			if err := json.Unmarshal([]byte(v), &strct.Id); err != nil {
				return err
			}
			idReceived = true
		default:
			return fmt.Errorf("additional property not allowed: %q", k)
		}
	}
	// check if command (a required property) was received
	if !commandReceived {
		return errors.New("\"command\" is required but was not present")
	}
	// check if expected_exit_codes (a required property) was received
	if !expected_exit_codesReceived {
		return errors.New("\"expected_exit_codes\" is required but was not present")
	}
	// check if id (a required property) was received
	if !idReceived {
		return errors.New("\"id\" is required but was not present")
	}
	return nil
}

func (strct *DoStep) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
	comma := false
	// "Id" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "id" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"id\": ")
	if tmp, err := json.Marshal(strct.Id); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Text" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "text" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"text\": ")
	if tmp, err := json.Marshal(strct.Text); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *DoStep) UnmarshalJSON(b []byte) error {
	idReceived := false
	textReceived := false
	var jsonMap map[string]json.RawMessage
	if err := json.Unmarshal(b, &jsonMap); err != nil {
		return err
	}
	// parse all the defined properties
	for k, v := range jsonMap {
		switch k {
		case "id":
			if err := json.Unmarshal([]byte(v), &strct.Id); err != nil {
				return err
			}
			idReceived = true
		case "text":
			if err := json.Unmarshal([]byte(v), &strct.Text); err != nil {
				return err
			}
			textReceived = true
		default:
			return fmt.Errorf("additional property not allowed: %q", k)
		}
	}
	// check if id (a required property) was received
	if !idReceived {
		return errors.New("\"id\" is required but was not present")
	}
	// check if text (a required property) was received
	if !textReceived {
		return errors.New("\"text\" is required but was not present")
	}
	return nil
}

func (strct *PlanOutput) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
	comma := false
	// "AcceptanceCriteria" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "acceptance_criteria" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"acceptance_criteria\": ")
	if tmp, err := json.Marshal(strct.AcceptanceCriteria); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "DoSteps" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "do_steps" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"do_steps\": ")
	if tmp, err := json.Marshal(strct.DoSteps); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *PlanOutput) UnmarshalJSON(b []byte) error {
	acceptance_criteriaReceived := false
	do_stepsReceived := false
	var jsonMap map[string]json.RawMessage
	if err := json.Unmarshal(b, &jsonMap); err != nil {
		return err
	}
	// parse all the defined properties
	for k, v := range jsonMap {
		switch k {
		case "acceptance_criteria":
			if err := json.Unmarshal([]byte(v), &strct.AcceptanceCriteria); err != nil {
				return err
			}
			acceptance_criteriaReceived = true
		case "do_steps":
			if err := json.Unmarshal([]byte(v), &strct.DoSteps); err != nil {
				return err
			}
			do_stepsReceived = true
		default:
			return fmt.Errorf("additional property not allowed: %q", k)
		}
	}
	// check if acceptance_criteria (a required property) was received
	if !acceptance_criteriaReceived {
		return errors.New("\"acceptance_criteria\" is required but was not present")
	}
	// check if do_steps (a required property) was received
	if !do_stepsReceived {
		return errors.New("\"do_steps\" is required but was not present")
	}
	return nil
}

func (strct *PlanResponse) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
	comma := false
	// "PlanOutput" field is required
	if strct.PlanOutput == nil {
		return nil, errors.New("plan_output is a required field")
	}
	// Marshal the "plan_output" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"plan_output\": ")
	if tmp, err := json.Marshal(strct.PlanOutput); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Status" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "status" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"status\": ")
	if tmp, err := json.Marshal(strct.Status); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// Marshal the "stop_reason" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"stop_reason\": ")
	if tmp, err := json.Marshal(strct.StopReason); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Summary" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "summary" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"summary\": ")
	if tmp, err := json.Marshal(strct.Summary); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *PlanResponse) UnmarshalJSON(b []byte) error {
	plan_outputReceived := false
	statusReceived := false
	summaryReceived := false
	var jsonMap map[string]json.RawMessage
	if err := json.Unmarshal(b, &jsonMap); err != nil {
		return err
	}
	// parse all the defined properties
	for k, v := range jsonMap {
		switch k {
		case "plan_output":
			if err := json.Unmarshal([]byte(v), &strct.PlanOutput); err != nil {
				return err
			}
			plan_outputReceived = true
		case "status":
			if err := json.Unmarshal([]byte(v), &strct.Status); err != nil {
				return err
			}
			statusReceived = true
		case "stop_reason":
			if err := json.Unmarshal([]byte(v), &strct.StopReason); err != nil {
				return err
			}
		case "summary":
			if err := json.Unmarshal([]byte(v), &strct.Summary); err != nil {
				return err
			}
			summaryReceived = true
		default:
			return fmt.Errorf("additional property not allowed: %q", k)
		}
	}
	// check if plan_output (a required property) was received
	if !plan_outputReceived {
		return errors.New("\"plan_output\" is required but was not present")
	}
	// check if status (a required property) was received
	if !statusReceived {
		return errors.New("\"status\" is required but was not present")
	}
	// check if summary (a required property) was received
	if !summaryReceived {
		return errors.New("\"summary\" is required but was not present")
	}
	return nil
}

func (strct *PlannedAcceptanceCriterion) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
	comma := false
	// "Checks" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "checks" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"checks\": ")
	if tmp, err := json.Marshal(strct.Checks); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Id" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "id" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"id\": ")
	if tmp, err := json.Marshal(strct.Id); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Text" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "text" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"text\": ")
	if tmp, err := json.Marshal(strct.Text); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *PlannedAcceptanceCriterion) UnmarshalJSON(b []byte) error {
	checksReceived := false
	idReceived := false
	textReceived := false
	var jsonMap map[string]json.RawMessage
	if err := json.Unmarshal(b, &jsonMap); err != nil {
		return err
	}
	// parse all the defined properties
	for k, v := range jsonMap {
		switch k {
		case "checks":
			if err := json.Unmarshal([]byte(v), &strct.Checks); err != nil {
				return err
			}
			checksReceived = true
		case "id":
			if err := json.Unmarshal([]byte(v), &strct.Id); err != nil {
				return err
			}
			idReceived = true
		case "text":
			if err := json.Unmarshal([]byte(v), &strct.Text); err != nil {
				return err
			}
			textReceived = true
		default:
			return fmt.Errorf("additional property not allowed: %q", k)
		}
	}
	// check if checks (a required property) was received
	if !checksReceived {
		return errors.New("\"checks\" is required but was not present")
	}
	// check if id (a required property) was received
	if !idReceived {
		return errors.New("\"id\" is required but was not present")
	}
	// check if text (a required property) was received
	if !textReceived {
		return errors.New("\"text\" is required but was not present")
	}
	return nil
}
