// Code generated by schema-generate. DO NOT EDIT.

package act

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
)

// AcceptanceResult
type AcceptanceResult struct {
	AcId   string `json:"ac_id"`
	Notes  string `json:"notes"`
	Result string `json:"result"`
}

// ActInput
type ActInput struct {
	AcceptanceResults []AcceptanceResult `json:"acceptance_results,omitempty"`
	Verdict           string             `json:"verdict"`
}

// ActRequest
type ActRequest struct {
	ActInput *ActInput `json:"act_input"`
	Paths    *Paths    `json:"paths"`
	Run      *Run      `json:"run"`
	Step     *Step     `json:"step"`
	Task     *Task     `json:"task"`
}

// Paths
type Paths struct {
	WorkspaceDir string `json:"workspace_dir"`
}

// Run
type Run struct {
	Id        string `json:"id"`
	Iteration int64  `json:"iteration"`
}

// Step
type Step struct {
	Index int64 `json:"index"`
}

// Task
type Task struct {
	Goal string `json:"goal"`
	Id   string `json:"id"`
}

func (strct *AcceptanceResult) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
	comma := false
	// "AcId" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "ac_id" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"ac_id\": ")
	if tmp, err := json.Marshal(strct.AcId); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Notes" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "notes" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"notes\": ")
	if tmp, err := json.Marshal(strct.Notes); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Result" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "result" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"result\": ")
	if tmp, err := json.Marshal(strct.Result); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *AcceptanceResult) UnmarshalJSON(b []byte) error {
	ac_idReceived := false
	notesReceived := false
	resultReceived := false
	var jsonMap map[string]json.RawMessage
	if err := json.Unmarshal(b, &jsonMap); err != nil {
		return err
	}
	// parse all the defined properties
	for k, v := range jsonMap {
		switch k {
		case "ac_id":
			if err := json.Unmarshal([]byte(v), &strct.AcId); err != nil {
				return err
			}
			ac_idReceived = true
		case "notes":
			if err := json.Unmarshal([]byte(v), &strct.Notes); err != nil {
				return err
			}
			notesReceived = true
		case "result":
			if err := json.Unmarshal([]byte(v), &strct.Result); err != nil {
				return err
			}
			resultReceived = true
		default:
			return fmt.Errorf("additional property not allowed: %q", k)
		}
	}
	// check if ac_id (a required property) was received
	if !ac_idReceived {
		return errors.New("\"ac_id\" is required but was not present")
	}
	// check if notes (a required property) was received
	if !notesReceived {
		return errors.New("\"notes\" is required but was not present")
	}
	// check if result (a required property) was received
	if !resultReceived {
		return errors.New("\"result\" is required but was not present")
	}
	return nil
}

func (strct *ActInput) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
	comma := false
	// Marshal the "acceptance_results" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"acceptance_results\": ")
	if tmp, err := json.Marshal(strct.AcceptanceResults); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Verdict" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "verdict" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"verdict\": ")
	if tmp, err := json.Marshal(strct.Verdict); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *ActInput) UnmarshalJSON(b []byte) error {
	verdictReceived := false
	var jsonMap map[string]json.RawMessage
	if err := json.Unmarshal(b, &jsonMap); err != nil {
		return err
	}
	// parse all the defined properties
	for k, v := range jsonMap {
		switch k {
		case "acceptance_results":
			if err := json.Unmarshal([]byte(v), &strct.AcceptanceResults); err != nil {
				return err
			}
		case "verdict":
			if err := json.Unmarshal([]byte(v), &strct.Verdict); err != nil {
				return err
			}
			verdictReceived = true
		default:
			return fmt.Errorf("additional property not allowed: %q", k)
		}
	}
	// check if verdict (a required property) was received
	if !verdictReceived {
		return errors.New("\"verdict\" is required but was not present")
	}
	return nil
}

func (strct *ActRequest) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
	comma := false
	// "ActInput" field is required
	if strct.ActInput == nil {
		return nil, errors.New("act_input is a required field")
	}
	// Marshal the "act_input" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"act_input\": ")
	if tmp, err := json.Marshal(strct.ActInput); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Paths" field is required
	if strct.Paths == nil {
		return nil, errors.New("paths is a required field")
	}
	// Marshal the "paths" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"paths\": ")
	if tmp, err := json.Marshal(strct.Paths); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Run" field is required
	if strct.Run == nil {
		return nil, errors.New("run is a required field")
	}
	// Marshal the "run" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"run\": ")
	if tmp, err := json.Marshal(strct.Run); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Step" field is required
	if strct.Step == nil {
		return nil, errors.New("step is a required field")
	}
	// Marshal the "step" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"step\": ")
	if tmp, err := json.Marshal(strct.Step); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Task" field is required
	if strct.Task == nil {
		return nil, errors.New("task is a required field")
	}
	// Marshal the "task" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"task\": ")
	if tmp, err := json.Marshal(strct.Task); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *ActRequest) UnmarshalJSON(b []byte) error {
	act_inputReceived := false
	pathsReceived := false
	runReceived := false
	stepReceived := false
	taskReceived := false
	var jsonMap map[string]json.RawMessage
	if err := json.Unmarshal(b, &jsonMap); err != nil {
		return err
	}
	// parse all the defined properties
	for k, v := range jsonMap {
		switch k {
		case "act_input":
			if err := json.Unmarshal([]byte(v), &strct.ActInput); err != nil {
				return err
			}
			act_inputReceived = true
		case "paths":
			if err := json.Unmarshal([]byte(v), &strct.Paths); err != nil {
				return err
			}
			pathsReceived = true
		case "run":
			if err := json.Unmarshal([]byte(v), &strct.Run); err != nil {
				return err
			}
			runReceived = true
		case "step":
			if err := json.Unmarshal([]byte(v), &strct.Step); err != nil {
				return err
			}
			stepReceived = true
		case "task":
			if err := json.Unmarshal([]byte(v), &strct.Task); err != nil {
				return err
			}
			taskReceived = true
		default:
			return fmt.Errorf("additional property not allowed: %q", k)
		}
	}
	// check if act_input (a required property) was received
	if !act_inputReceived {
		return errors.New("\"act_input\" is required but was not present")
	}
	// check if paths (a required property) was received
	if !pathsReceived {
		return errors.New("\"paths\" is required but was not present")
	}
	// check if run (a required property) was received
	if !runReceived {
		return errors.New("\"run\" is required but was not present")
	}
	// check if step (a required property) was received
	if !stepReceived {
		return errors.New("\"step\" is required but was not present")
	}
	// check if task (a required property) was received
	if !taskReceived {
		return errors.New("\"task\" is required but was not present")
	}
	return nil
}

func (strct *Paths) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
	comma := false
	// "WorkspaceDir" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "workspace_dir" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"workspace_dir\": ")
	if tmp, err := json.Marshal(strct.WorkspaceDir); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Paths) UnmarshalJSON(b []byte) error {
	workspace_dirReceived := false
	var jsonMap map[string]json.RawMessage
	if err := json.Unmarshal(b, &jsonMap); err != nil {
		return err
	}
	// parse all the defined properties
	for k, v := range jsonMap {
		switch k {
		case "workspace_dir":
			if err := json.Unmarshal([]byte(v), &strct.WorkspaceDir); err != nil {
				return err
			}
			workspace_dirReceived = true
		default:
			return fmt.Errorf("additional property not allowed: %q", k)
		}
	}
	// check if workspace_dir (a required property) was received
	if !workspace_dirReceived {
		return errors.New("\"workspace_dir\" is required but was not present")
	}
	return nil
}

func (strct *Run) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
	comma := false
	// "Id" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "id" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"id\": ")
	if tmp, err := json.Marshal(strct.Id); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Iteration" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "iteration" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"iteration\": ")
	if tmp, err := json.Marshal(strct.Iteration); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Run) UnmarshalJSON(b []byte) error {
	idReceived := false
	iterationReceived := false
	var jsonMap map[string]json.RawMessage
	if err := json.Unmarshal(b, &jsonMap); err != nil {
		return err
	}
	// parse all the defined properties
	for k, v := range jsonMap {
		switch k {
		case "id":
			if err := json.Unmarshal([]byte(v), &strct.Id); err != nil {
				return err
			}
			idReceived = true
		case "iteration":
			if err := json.Unmarshal([]byte(v), &strct.Iteration); err != nil {
				return err
			}
			iterationReceived = true
		default:
			return fmt.Errorf("additional property not allowed: %q", k)
		}
	}
	// check if id (a required property) was received
	if !idReceived {
		return errors.New("\"id\" is required but was not present")
	}
	// check if iteration (a required property) was received
	if !iterationReceived {
		return errors.New("\"iteration\" is required but was not present")
	}
	return nil
}

func (strct *Step) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
	comma := false
	// "Index" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "index" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"index\": ")
	if tmp, err := json.Marshal(strct.Index); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Step) UnmarshalJSON(b []byte) error {
	indexReceived := false
	var jsonMap map[string]json.RawMessage
	if err := json.Unmarshal(b, &jsonMap); err != nil {
		return err
	}
	// parse all the defined properties
	for k, v := range jsonMap {
		switch k {
		case "index":
			if err := json.Unmarshal([]byte(v), &strct.Index); err != nil {
				return err
			}
			indexReceived = true
		default:
			return fmt.Errorf("additional property not allowed: %q", k)
		}
	}
	// check if index (a required property) was received
	if !indexReceived {
		return errors.New("\"index\" is required but was not present")
	}
	return nil
}

func (strct *Task) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
	comma := false
	// "Goal" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "goal" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"goal\": ")
	if tmp, err := json.Marshal(strct.Goal); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Id" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "id" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"id\": ")
	if tmp, err := json.Marshal(strct.Id); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Task) UnmarshalJSON(b []byte) error {
	goalReceived := false
	idReceived := false
	var jsonMap map[string]json.RawMessage
	if err := json.Unmarshal(b, &jsonMap); err != nil {
		return err
	}
	// parse all the defined properties
	for k, v := range jsonMap {
		switch k {
		case "goal":
			if err := json.Unmarshal([]byte(v), &strct.Goal); err != nil {
				return err
			}
			goalReceived = true
		case "id":
			if err := json.Unmarshal([]byte(v), &strct.Id); err != nil {
				return err
			}
			idReceived = true
		default:
			return fmt.Errorf("additional property not allowed: %q", k)
		}
	}
	// check if goal (a required property) was received
	if !goalReceived {
		return errors.New("\"goal\" is required but was not present")
	}
	// check if id (a required property) was received
	if !idReceived {
		return errors.New("\"id\" is required but was not present")
	}
	return nil
}
