// Code generated by schema-generate. DO NOT EDIT.

package act

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
)

// ActOutput
type ActOutput struct {
	Decision  string `json:"decision"`
	Next      *Next  `json:"next,omitempty"`
	Rationale string `json:"rationale,omitempty"`
}

// ActResponse
type ActResponse struct {
	ActOutput  *ActOutput `json:"act_output"`
	Status     string     `json:"status"`
	StopReason string     `json:"stop_reason,omitempty"`
	Summary    string     `json:"summary"`
}

// Next
type Next struct {
	Notes       string `json:"notes"`
	Recommended bool   `json:"recommended"`
}

func (strct *ActOutput) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
	comma := false
	// "Decision" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "decision" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"decision\": ")
	if tmp, err := json.Marshal(strct.Decision); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// Marshal the "next" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"next\": ")
	if tmp, err := json.Marshal(strct.Next); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// Marshal the "rationale" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"rationale\": ")
	if tmp, err := json.Marshal(strct.Rationale); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *ActOutput) UnmarshalJSON(b []byte) error {
	decisionReceived := false
	var jsonMap map[string]json.RawMessage
	if err := json.Unmarshal(b, &jsonMap); err != nil {
		return err
	}
	// parse all the defined properties
	for k, v := range jsonMap {
		switch k {
		case "decision":
			if err := json.Unmarshal([]byte(v), &strct.Decision); err != nil {
				return err
			}
			decisionReceived = true
		case "next":
			if err := json.Unmarshal([]byte(v), &strct.Next); err != nil {
				return err
			}
		case "rationale":
			if err := json.Unmarshal([]byte(v), &strct.Rationale); err != nil {
				return err
			}
		default:
			return fmt.Errorf("additional property not allowed: %q", k)
		}
	}
	// check if decision (a required property) was received
	if !decisionReceived {
		return errors.New("\"decision\" is required but was not present")
	}
	return nil
}

func (strct *ActResponse) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
	comma := false
	// "ActOutput" field is required
	if strct.ActOutput == nil {
		return nil, errors.New("act_output is a required field")
	}
	// Marshal the "act_output" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"act_output\": ")
	if tmp, err := json.Marshal(strct.ActOutput); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Status" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "status" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"status\": ")
	if tmp, err := json.Marshal(strct.Status); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// Marshal the "stop_reason" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"stop_reason\": ")
	if tmp, err := json.Marshal(strct.StopReason); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Summary" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "summary" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"summary\": ")
	if tmp, err := json.Marshal(strct.Summary); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *ActResponse) UnmarshalJSON(b []byte) error {
	act_outputReceived := false
	statusReceived := false
	summaryReceived := false
	var jsonMap map[string]json.RawMessage
	if err := json.Unmarshal(b, &jsonMap); err != nil {
		return err
	}
	// parse all the defined properties
	for k, v := range jsonMap {
		switch k {
		case "act_output":
			if err := json.Unmarshal([]byte(v), &strct.ActOutput); err != nil {
				return err
			}
			act_outputReceived = true
		case "status":
			if err := json.Unmarshal([]byte(v), &strct.Status); err != nil {
				return err
			}
			statusReceived = true
		case "stop_reason":
			if err := json.Unmarshal([]byte(v), &strct.StopReason); err != nil {
				return err
			}
		case "summary":
			if err := json.Unmarshal([]byte(v), &strct.Summary); err != nil {
				return err
			}
			summaryReceived = true
		default:
			return fmt.Errorf("additional property not allowed: %q", k)
		}
	}
	// check if act_output (a required property) was received
	if !act_outputReceived {
		return errors.New("\"act_output\" is required but was not present")
	}
	// check if status (a required property) was received
	if !statusReceived {
		return errors.New("\"status\" is required but was not present")
	}
	// check if summary (a required property) was received
	if !summaryReceived {
		return errors.New("\"summary\" is required but was not present")
	}
	return nil
}

func (strct *Next) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
	comma := false
	// "Notes" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "notes" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"notes\": ")
	if tmp, err := json.Marshal(strct.Notes); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Recommended" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "recommended" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"recommended\": ")
	if tmp, err := json.Marshal(strct.Recommended); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Next) UnmarshalJSON(b []byte) error {
	notesReceived := false
	recommendedReceived := false
	var jsonMap map[string]json.RawMessage
	if err := json.Unmarshal(b, &jsonMap); err != nil {
		return err
	}
	// parse all the defined properties
	for k, v := range jsonMap {
		switch k {
		case "notes":
			if err := json.Unmarshal([]byte(v), &strct.Notes); err != nil {
				return err
			}
			notesReceived = true
		case "recommended":
			if err := json.Unmarshal([]byte(v), &strct.Recommended); err != nil {
				return err
			}
			recommendedReceived = true
		default:
			return fmt.Errorf("additional property not allowed: %q", k)
		}
	}
	// check if notes (a required property) was received
	if !notesReceived {
		return errors.New("\"notes\" is required but was not present")
	}
	// check if recommended (a required property) was received
	if !recommendedReceived {
		return errors.New("\"recommended\" is required but was not present")
	}
	return nil
}
