// Code generated by schema-generate. DO NOT EDIT.

package do

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
)

// DoOutput
type DoOutput struct {
	ExecutedStepIds []string `json:"executed_step_ids"`
}

// DoResponse
type DoResponse struct {
	DoOutput   *DoOutput `json:"do_output"`
	Status     string    `json:"status"`
	StopReason string    `json:"stop_reason,omitempty"`
	Summary    string    `json:"summary"`
}

func (strct *DoOutput) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
	comma := false
	// "ExecutedStepIds" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "executed_step_ids" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"executed_step_ids\": ")
	if tmp, err := json.Marshal(strct.ExecutedStepIds); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *DoOutput) UnmarshalJSON(b []byte) error {
	executed_step_idsReceived := false
	var jsonMap map[string]json.RawMessage
	if err := json.Unmarshal(b, &jsonMap); err != nil {
		return err
	}
	// parse all the defined properties
	for k, v := range jsonMap {
		switch k {
		case "executed_step_ids":
			if err := json.Unmarshal([]byte(v), &strct.ExecutedStepIds); err != nil {
				return err
			}
			executed_step_idsReceived = true
		default:
			return fmt.Errorf("additional property not allowed: %q", k)
		}
	}
	// check if executed_step_ids (a required property) was received
	if !executed_step_idsReceived {
		return errors.New("\"executed_step_ids\" is required but was not present")
	}
	return nil
}

func (strct *DoResponse) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
	comma := false
	// "DoOutput" field is required
	if strct.DoOutput == nil {
		return nil, errors.New("do_output is a required field")
	}
	// Marshal the "do_output" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"do_output\": ")
	if tmp, err := json.Marshal(strct.DoOutput); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Status" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "status" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"status\": ")
	if tmp, err := json.Marshal(strct.Status); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// Marshal the "stop_reason" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"stop_reason\": ")
	if tmp, err := json.Marshal(strct.StopReason); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Summary" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "summary" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"summary\": ")
	if tmp, err := json.Marshal(strct.Summary); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *DoResponse) UnmarshalJSON(b []byte) error {
	do_outputReceived := false
	statusReceived := false
	summaryReceived := false
	var jsonMap map[string]json.RawMessage
	if err := json.Unmarshal(b, &jsonMap); err != nil {
		return err
	}
	// parse all the defined properties
	for k, v := range jsonMap {
		switch k {
		case "do_output":
			if err := json.Unmarshal([]byte(v), &strct.DoOutput); err != nil {
				return err
			}
			do_outputReceived = true
		case "status":
			if err := json.Unmarshal([]byte(v), &strct.Status); err != nil {
				return err
			}
			statusReceived = true
		case "stop_reason":
			if err := json.Unmarshal([]byte(v), &strct.StopReason); err != nil {
				return err
			}
		case "summary":
			if err := json.Unmarshal([]byte(v), &strct.Summary); err != nil {
				return err
			}
			summaryReceived = true
		default:
			return fmt.Errorf("additional property not allowed: %q", k)
		}
	}
	// check if do_output (a required property) was received
	if !do_outputReceived {
		return errors.New("\"do_output\" is required but was not present")
	}
	// check if status (a required property) was received
	if !statusReceived {
		return errors.New("\"status\" is required but was not present")
	}
	// check if summary (a required property) was received
	if !summaryReceived {
		return errors.New("\"summary\" is required but was not present")
	}
	return nil
}
