package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/normahq/norma/pkg/runtime/appconfig"
	"gopkg.in/yaml.v3"
)

const testRelayRootAgentGemini = "gemini"

func TestInitCommand_CreatesRelayConfigWithSelectedRootAgent(t *testing.T) {
	workingDir := t.TempDir()
	prevWD, err := os.Getwd()
	if err != nil {
		t.Fatalf("get wd: %v", err)
	}
	t.Cleanup(func() {
		_ = os.Chdir(prevWD)
	})
	if err := os.Chdir(workingDir); err != nil {
		t.Fatalf("chdir: %v", err)
	}

	prevInput := relayInitInput
	prevOutput := relayInitOutput
	prevInteractive := relayInitIsInteractive
	t.Cleanup(func() {
		relayInitInput = prevInput
		relayInitOutput = prevOutput
		relayInitIsInteractive = prevInteractive
	})

	relayInitInput = strings.NewReader("")
	relayInitOutput = &bytes.Buffer{}
	relayInitIsInteractive = func() bool { return false }

	cmd := initCommand()
	cmd.SetArgs([]string{"--relay-root-agent", testRelayRootAgentGemini})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("init command failed: %v", err)
	}

	configPath := filepath.Join(workingDir, ".norma", relayConfigFileName)
	content, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("read config: %v", err)
	}

	var doc map[string]any
	if err := yaml.Unmarshal(content, &doc); err != nil {
		t.Fatalf("unmarshal config: %v", err)
	}
	relaySection, ok := toStringAnyMap(doc["relay"])
	if !ok {
		t.Fatalf("relay section missing in %s", configPath)
	}
	if got := relaySection["root_agent"]; got != testRelayRootAgentGemini {
		t.Fatalf("relay.root_agent = %#v, want %s", got, testRelayRootAgentGemini)
	}
	telegramSection, ok := toStringAnyMap(relaySection["telegram"])
	if !ok {
		t.Fatal("relay.telegram section missing in generated config")
	}
	if got := telegramSection["token"]; got != "" {
		t.Fatalf("relay.telegram.token = %#v, want empty string in non-interactive mode", got)
	}

	normaSection, ok := toStringAnyMap(doc["norma"])
	if !ok {
		t.Fatal("norma section missing in generated config")
	}
	agents, ok := toStringAnyMap(normaSection["agents"])
	if !ok {
		t.Fatal("norma.agents missing in generated config")
	}
	if _, ok := agents["custom_generic"]; ok {
		t.Fatal("norma.agents.custom_generic must not be generated by relay init")
	}
	if _, ok := agents["custom_generic_acp_agent"]; ok {
		t.Fatal("norma.agents.custom_generic_acp_agent must not be generated by relay init")
	}

	for _, key := range []string{
		"root_agent",
		"telegram",
		"auth",
		"logger",
		"working_dir",
		"state_dir",
		"workspace",
		"mcp",
		"internal_mcp",
	} {
		if _, ok := relaySection[key]; !ok {
			t.Fatalf("relay.%s is missing in generated config", key)
		}
	}
	mcpSection, ok := toStringAnyMap(relaySection["mcp"])
	if !ok {
		t.Fatal("relay.mcp section is missing or invalid")
	}
	if _, ok := mcpSection["address"]; !ok {
		t.Fatal("relay.mcp.address is missing in generated config")
	}
}

func TestInitCommand_InteractivePromptsAndStoresTelegramToken(t *testing.T) {
	workingDir := t.TempDir()
	prevWD, err := os.Getwd()
	if err != nil {
		t.Fatalf("get wd: %v", err)
	}
	t.Cleanup(func() {
		_ = os.Chdir(prevWD)
	})
	if err := os.Chdir(workingDir); err != nil {
		t.Fatalf("chdir: %v", err)
	}

	prevInput := relayInitInput
	prevOutput := relayInitOutput
	prevInteractive := relayInitIsInteractive
	t.Cleanup(func() {
		relayInitInput = prevInput
		relayInitOutput = prevOutput
		relayInitIsInteractive = prevInteractive
	})

	relayInitInput = strings.NewReader(testRelayRootAgentGemini + "\nmy-token\n")
	relayInitOutput = &bytes.Buffer{}
	relayInitIsInteractive = func() bool { return true }

	cmd := initCommand()
	cmd.SetArgs([]string{})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("init command failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(workingDir, ".norma", relayConfigFileName))
	if err != nil {
		t.Fatalf("read config: %v", err)
	}
	var doc map[string]any
	if err := yaml.Unmarshal(content, &doc); err != nil {
		t.Fatalf("unmarshal config: %v", err)
	}
	relaySection, ok := toStringAnyMap(doc["relay"])
	if !ok {
		t.Fatal("relay section missing in generated config")
	}
	if got := relaySection["root_agent"]; got != testRelayRootAgentGemini {
		t.Fatalf("relay.root_agent = %#v, want %s", got, testRelayRootAgentGemini)
	}
	telegramSection, ok := toStringAnyMap(relaySection["telegram"])
	if !ok {
		t.Fatal("relay.telegram section missing in generated config")
	}
	if got := telegramSection["token"]; got != "my-token" {
		t.Fatalf("relay.telegram.token = %#v, want my-token", got)
	}
}

func TestInitCommand_InteractiveAllowsEmptyTelegramToken(t *testing.T) {
	workingDir := t.TempDir()
	prevWD, err := os.Getwd()
	if err != nil {
		t.Fatalf("get wd: %v", err)
	}
	t.Cleanup(func() {
		_ = os.Chdir(prevWD)
	})
	if err := os.Chdir(workingDir); err != nil {
		t.Fatalf("chdir: %v", err)
	}

	prevInput := relayInitInput
	prevOutput := relayInitOutput
	prevInteractive := relayInitIsInteractive
	t.Cleanup(func() {
		relayInitInput = prevInput
		relayInitOutput = prevOutput
		relayInitIsInteractive = prevInteractive
	})

	relayInitInput = strings.NewReader(testRelayRootAgentGemini + "\n\n")
	relayInitOutput = &bytes.Buffer{}
	relayInitIsInteractive = func() bool { return true }

	cmd := initCommand()
	cmd.SetArgs([]string{})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("init command failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(workingDir, ".norma", relayConfigFileName))
	if err != nil {
		t.Fatalf("read config: %v", err)
	}
	var doc map[string]any
	if err := yaml.Unmarshal(content, &doc); err != nil {
		t.Fatalf("unmarshal config: %v", err)
	}
	relaySection, ok := toStringAnyMap(doc["relay"])
	if !ok {
		t.Fatal("relay section missing in generated config")
	}
	telegramSection, ok := toStringAnyMap(relaySection["telegram"])
	if !ok {
		t.Fatal("relay.telegram section missing in generated config")
	}
	if got := telegramSection["token"]; got != "" {
		t.Fatalf("relay.telegram.token = %#v, want empty string", got)
	}
}

func TestInitCommand_FailsWhenConfigAlreadyExists(t *testing.T) {
	workingDir := t.TempDir()
	prevWD, err := os.Getwd()
	if err != nil {
		t.Fatalf("get wd: %v", err)
	}
	t.Cleanup(func() {
		_ = os.Chdir(prevWD)
	})
	if err := os.Chdir(workingDir); err != nil {
		t.Fatalf("chdir: %v", err)
	}

	configPath := filepath.Join(workingDir, ".norma", relayConfigFileName)
	if err := os.MkdirAll(filepath.Dir(configPath), 0o700); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(configPath, []byte("relay:\n  root_agent: existing\n"), 0o600); err != nil {
		t.Fatalf("write existing config: %v", err)
	}

	cmd := initCommand()
	cmd.SetArgs([]string{"--relay-root-agent", testRelayRootAgentGemini})
	err = cmd.Execute()
	if err == nil {
		t.Fatal("expected error when relay config already exists")
	}
	if !strings.Contains(err.Error(), "already exists") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestChooseRelayRootAgent_NonInteractiveRequiresFlag(t *testing.T) {
	_, err := chooseRelayRootAgent("", []string{"a", "b"}, strings.NewReader(""), &bytes.Buffer{}, false)
	if err == nil {
		t.Fatal("expected error in non-interactive mode without --relay-root-agent")
	}
	if !strings.Contains(err.Error(), "--relay-root-agent is required in non-interactive mode") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestChooseRelayRootAgent_InteractiveSelectionByNumber(t *testing.T) {
	var out bytes.Buffer
	got, err := chooseRelayRootAgent("", []string{"alpha", "beta"}, strings.NewReader("2\n"), &out, true)
	if err != nil {
		t.Fatalf("chooseRelayRootAgent: %v", err)
	}
	if got != "beta" {
		t.Fatalf("selected = %q, want beta", got)
	}
}

func TestInitCommand_GeneratedConfigLoadableByRelayLoader(t *testing.T) {
	workingDir := t.TempDir()
	prevWD, err := os.Getwd()
	if err != nil {
		t.Fatalf("get wd: %v", err)
	}
	t.Cleanup(func() {
		_ = os.Chdir(prevWD)
	})
	if err := os.Chdir(workingDir); err != nil {
		t.Fatalf("chdir: %v", err)
	}

	prevInput := relayInitInput
	prevOutput := relayInitOutput
	prevInteractive := relayInitIsInteractive
	t.Cleanup(func() {
		relayInitInput = prevInput
		relayInitOutput = prevOutput
		relayInitIsInteractive = prevInteractive
	})
	relayInitInput = strings.NewReader("")
	relayInitOutput = &bytes.Buffer{}
	relayInitIsInteractive = func() bool { return false }

	cmd := initCommand()
	cmd.SetArgs([]string{"--relay-root-agent", "gemini"})
	if err := cmd.Execute(); err != nil {
		t.Fatalf("init command failed: %v", err)
	}

	var doc relayTestConfigDocument
	selectedProfile, err := appconfig.LoadConfigDocument(
		appconfig.RuntimeLoadOptions{WorkingDir: workingDir},
		appconfig.AppLoadOptions{
			AppName:      "relay",
			DefaultsYAML: defaultRelayConfig,
		},
		&doc,
	)
	if err != nil {
		t.Fatalf("LoadConfigDocument: %v", err)
	}
	if selectedProfile != "default" {
		t.Fatalf("selected profile = %q, want default", selectedProfile)
	}
	if got := doc.Relay.RootAgent; got != testRelayRootAgentGemini {
		t.Fatalf("doc.Relay.RootAgent = %q, want %s", got, testRelayRootAgentGemini)
	}
}
