// Code generated by schema-generate. DO NOT EDIT.

package check

import (
    "bytes"
    "errors"
    "encoding/json"
)

// Budgets 
type Budgets struct {
}

// CheckInput 
type CheckInput struct {
  AcceptanceCriteriaEffective []interface{} `json:"acceptance_criteria_effective"`
  DoExecution *DoExecution `json:"do_execution"`
  WorkPlan *WorkPlan `json:"work_plan"`
}

// CheckRequest 
type CheckRequest struct {
  Budgets *Budgets `json:"budgets,omitempty"`
  CheckInput *CheckInput `json:"check_input"`
  Context *Context `json:"context,omitempty"`
  Paths *Paths `json:"paths"`
  Run *Run `json:"run"`
  Step *Step `json:"step"`
  StopReasonsAllowed []string `json:"stop_reasons_allowed,omitempty"`
  Task *Task `json:"task"`
}

// Context 
type Context struct {
}

// DoExecution 
type DoExecution struct {
}

// Paths 
type Paths struct {
  CodeRoot string `json:"code_root"`
  RunDir string `json:"run_dir"`
  WorkspaceDir string `json:"workspace_dir"`
  WorkspaceMode string `json:"workspace_mode"`
}

// Run 
type Run struct {
  Id string `json:"id"`
  Iteration int64 `json:"iteration"`
}

// Step 
type Step struct {
  Dir string `json:"dir"`
  Index int64 `json:"index"`
  Name string `json:"name"`
}

// Task 
type Task struct {
  AcceptanceCriteria []interface{} `json:"acceptance_criteria"`
  Description string `json:"description"`
  Id string `json:"id"`
  Title string `json:"title"`
}

// WorkPlan 
type WorkPlan struct {
}

func (strct *CheckInput) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "AcceptanceCriteriaEffective" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "acceptance_criteria_effective" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"acceptance_criteria_effective\": ")
	if tmp, err := json.Marshal(strct.AcceptanceCriteriaEffective); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "DoExecution" field is required
    if strct.DoExecution == nil {
        return nil, errors.New("do_execution is a required field")
    }
    // Marshal the "do_execution" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"do_execution\": ")
	if tmp, err := json.Marshal(strct.DoExecution); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "WorkPlan" field is required
    if strct.WorkPlan == nil {
        return nil, errors.New("work_plan is a required field")
    }
    // Marshal the "work_plan" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"work_plan\": ")
	if tmp, err := json.Marshal(strct.WorkPlan); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *CheckInput) UnmarshalJSON(b []byte) error {
    acceptance_criteria_effectiveReceived := false
    do_executionReceived := false
    work_planReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "acceptance_criteria_effective":
            if err := json.Unmarshal([]byte(v), &strct.AcceptanceCriteriaEffective); err != nil {
                return err
             }
            acceptance_criteria_effectiveReceived = true
        case "do_execution":
            if err := json.Unmarshal([]byte(v), &strct.DoExecution); err != nil {
                return err
             }
            do_executionReceived = true
        case "work_plan":
            if err := json.Unmarshal([]byte(v), &strct.WorkPlan); err != nil {
                return err
             }
            work_planReceived = true
        }
    }
    // check if acceptance_criteria_effective (a required property) was received
    if !acceptance_criteria_effectiveReceived {
        return errors.New("\"acceptance_criteria_effective\" is required but was not present")
    }
    // check if do_execution (a required property) was received
    if !do_executionReceived {
        return errors.New("\"do_execution\" is required but was not present")
    }
    // check if work_plan (a required property) was received
    if !work_planReceived {
        return errors.New("\"work_plan\" is required but was not present")
    }
    return nil
}

func (strct *CheckRequest) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // Marshal the "budgets" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"budgets\": ")
	if tmp, err := json.Marshal(strct.Budgets); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "CheckInput" field is required
    if strct.CheckInput == nil {
        return nil, errors.New("check_input is a required field")
    }
    // Marshal the "check_input" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"check_input\": ")
	if tmp, err := json.Marshal(strct.CheckInput); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "context" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"context\": ")
	if tmp, err := json.Marshal(strct.Context); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "Paths" field is required
    if strct.Paths == nil {
        return nil, errors.New("paths is a required field")
    }
    // Marshal the "paths" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"paths\": ")
	if tmp, err := json.Marshal(strct.Paths); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "Run" field is required
    if strct.Run == nil {
        return nil, errors.New("run is a required field")
    }
    // Marshal the "run" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"run\": ")
	if tmp, err := json.Marshal(strct.Run); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "Step" field is required
    if strct.Step == nil {
        return nil, errors.New("step is a required field")
    }
    // Marshal the "step" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"step\": ")
	if tmp, err := json.Marshal(strct.Step); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "stop_reasons_allowed" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"stop_reasons_allowed\": ")
	if tmp, err := json.Marshal(strct.StopReasonsAllowed); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "Task" field is required
    if strct.Task == nil {
        return nil, errors.New("task is a required field")
    }
    // Marshal the "task" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"task\": ")
	if tmp, err := json.Marshal(strct.Task); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *CheckRequest) UnmarshalJSON(b []byte) error {
    check_inputReceived := false
    pathsReceived := false
    runReceived := false
    stepReceived := false
    taskReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "budgets":
            if err := json.Unmarshal([]byte(v), &strct.Budgets); err != nil {
                return err
             }
        case "check_input":
            if err := json.Unmarshal([]byte(v), &strct.CheckInput); err != nil {
                return err
             }
            check_inputReceived = true
        case "context":
            if err := json.Unmarshal([]byte(v), &strct.Context); err != nil {
                return err
             }
        case "paths":
            if err := json.Unmarshal([]byte(v), &strct.Paths); err != nil {
                return err
             }
            pathsReceived = true
        case "run":
            if err := json.Unmarshal([]byte(v), &strct.Run); err != nil {
                return err
             }
            runReceived = true
        case "step":
            if err := json.Unmarshal([]byte(v), &strct.Step); err != nil {
                return err
             }
            stepReceived = true
        case "stop_reasons_allowed":
            if err := json.Unmarshal([]byte(v), &strct.StopReasonsAllowed); err != nil {
                return err
             }
        case "task":
            if err := json.Unmarshal([]byte(v), &strct.Task); err != nil {
                return err
             }
            taskReceived = true
        }
    }
    // check if check_input (a required property) was received
    if !check_inputReceived {
        return errors.New("\"check_input\" is required but was not present")
    }
    // check if paths (a required property) was received
    if !pathsReceived {
        return errors.New("\"paths\" is required but was not present")
    }
    // check if run (a required property) was received
    if !runReceived {
        return errors.New("\"run\" is required but was not present")
    }
    // check if step (a required property) was received
    if !stepReceived {
        return errors.New("\"step\" is required but was not present")
    }
    // check if task (a required property) was received
    if !taskReceived {
        return errors.New("\"task\" is required but was not present")
    }
    return nil
}

func (strct *Paths) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "CodeRoot" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "code_root" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"code_root\": ")
	if tmp, err := json.Marshal(strct.CodeRoot); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "RunDir" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "run_dir" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"run_dir\": ")
	if tmp, err := json.Marshal(strct.RunDir); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "WorkspaceDir" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "workspace_dir" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"workspace_dir\": ")
	if tmp, err := json.Marshal(strct.WorkspaceDir); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "WorkspaceMode" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "workspace_mode" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"workspace_mode\": ")
	if tmp, err := json.Marshal(strct.WorkspaceMode); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Paths) UnmarshalJSON(b []byte) error {
    code_rootReceived := false
    run_dirReceived := false
    workspace_dirReceived := false
    workspace_modeReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "code_root":
            if err := json.Unmarshal([]byte(v), &strct.CodeRoot); err != nil {
                return err
             }
            code_rootReceived = true
        case "run_dir":
            if err := json.Unmarshal([]byte(v), &strct.RunDir); err != nil {
                return err
             }
            run_dirReceived = true
        case "workspace_dir":
            if err := json.Unmarshal([]byte(v), &strct.WorkspaceDir); err != nil {
                return err
             }
            workspace_dirReceived = true
        case "workspace_mode":
            if err := json.Unmarshal([]byte(v), &strct.WorkspaceMode); err != nil {
                return err
             }
            workspace_modeReceived = true
        }
    }
    // check if code_root (a required property) was received
    if !code_rootReceived {
        return errors.New("\"code_root\" is required but was not present")
    }
    // check if run_dir (a required property) was received
    if !run_dirReceived {
        return errors.New("\"run_dir\" is required but was not present")
    }
    // check if workspace_dir (a required property) was received
    if !workspace_dirReceived {
        return errors.New("\"workspace_dir\" is required but was not present")
    }
    // check if workspace_mode (a required property) was received
    if !workspace_modeReceived {
        return errors.New("\"workspace_mode\" is required but was not present")
    }
    return nil
}

func (strct *Run) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "Id" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "id" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"id\": ")
	if tmp, err := json.Marshal(strct.Id); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "Iteration" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "iteration" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"iteration\": ")
	if tmp, err := json.Marshal(strct.Iteration); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Run) UnmarshalJSON(b []byte) error {
    idReceived := false
    iterationReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "id":
            if err := json.Unmarshal([]byte(v), &strct.Id); err != nil {
                return err
             }
            idReceived = true
        case "iteration":
            if err := json.Unmarshal([]byte(v), &strct.Iteration); err != nil {
                return err
             }
            iterationReceived = true
        }
    }
    // check if id (a required property) was received
    if !idReceived {
        return errors.New("\"id\" is required but was not present")
    }
    // check if iteration (a required property) was received
    if !iterationReceived {
        return errors.New("\"iteration\" is required but was not present")
    }
    return nil
}

func (strct *Step) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "Dir" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "dir" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"dir\": ")
	if tmp, err := json.Marshal(strct.Dir); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "Index" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "index" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"index\": ")
	if tmp, err := json.Marshal(strct.Index); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "Name" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "name" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"name\": ")
	if tmp, err := json.Marshal(strct.Name); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Step) UnmarshalJSON(b []byte) error {
    dirReceived := false
    indexReceived := false
    nameReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "dir":
            if err := json.Unmarshal([]byte(v), &strct.Dir); err != nil {
                return err
             }
            dirReceived = true
        case "index":
            if err := json.Unmarshal([]byte(v), &strct.Index); err != nil {
                return err
             }
            indexReceived = true
        case "name":
            if err := json.Unmarshal([]byte(v), &strct.Name); err != nil {
                return err
             }
            nameReceived = true
        }
    }
    // check if dir (a required property) was received
    if !dirReceived {
        return errors.New("\"dir\" is required but was not present")
    }
    // check if index (a required property) was received
    if !indexReceived {
        return errors.New("\"index\" is required but was not present")
    }
    // check if name (a required property) was received
    if !nameReceived {
        return errors.New("\"name\" is required but was not present")
    }
    return nil
}

func (strct *Task) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "AcceptanceCriteria" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "acceptance_criteria" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"acceptance_criteria\": ")
	if tmp, err := json.Marshal(strct.AcceptanceCriteria); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "Description" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "description" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"description\": ")
	if tmp, err := json.Marshal(strct.Description); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "Id" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "id" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"id\": ")
	if tmp, err := json.Marshal(strct.Id); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "Title" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "title" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"title\": ")
	if tmp, err := json.Marshal(strct.Title); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Task) UnmarshalJSON(b []byte) error {
    acceptance_criteriaReceived := false
    descriptionReceived := false
    idReceived := false
    titleReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "acceptance_criteria":
            if err := json.Unmarshal([]byte(v), &strct.AcceptanceCriteria); err != nil {
                return err
             }
            acceptance_criteriaReceived = true
        case "description":
            if err := json.Unmarshal([]byte(v), &strct.Description); err != nil {
                return err
             }
            descriptionReceived = true
        case "id":
            if err := json.Unmarshal([]byte(v), &strct.Id); err != nil {
                return err
             }
            idReceived = true
        case "title":
            if err := json.Unmarshal([]byte(v), &strct.Title); err != nil {
                return err
             }
            titleReceived = true
        }
    }
    // check if acceptance_criteria (a required property) was received
    if !acceptance_criteriaReceived {
        return errors.New("\"acceptance_criteria\" is required but was not present")
    }
    // check if description (a required property) was received
    if !descriptionReceived {
        return errors.New("\"description\" is required but was not present")
    }
    // check if id (a required property) was received
    if !idReceived {
        return errors.New("\"id\" is required but was not present")
    }
    // check if title (a required property) was received
    if !titleReceived {
        return errors.New("\"title\" is required but was not present")
    }
    return nil
}
