// Code generated by schema-generate. DO NOT EDIT.

package plan

import (
    "bytes"
    "encoding/json"
    "errors"
)

// AcceptanceCriteria 
type AcceptanceCriteria struct {
  Baseline []interface{} `json:"baseline"`
  Effective []interface{} `json:"effective"`
}

// Plan 
type Plan struct {
  AcceptanceCriteria *AcceptanceCriteria `json:"acceptance_criteria"`
  Constraints []string `json:"constraints,omitempty"`
  Goal string `json:"goal"`
  TaskId string `json:"task_id"`
  WorkPlan *WorkPlan `json:"work_plan"`
}

// Progress 
type Progress struct {
  Details []string `json:"details"`
  Title string `json:"title"`
}

// Root 
type Root struct {
  Plan *Plan `json:"plan"`
  Progress *Progress `json:"progress"`
  Status string `json:"status"`
  StopReason string `json:"stop_reason,omitempty"`
  Summary *Summary `json:"summary"`
}

// Summary 
type Summary struct {
  Text string `json:"text"`
}

// WorkPlan 
type WorkPlan struct {
  CheckSteps []interface{} `json:"check_steps"`
  DoSteps []interface{} `json:"do_steps"`
  StopTriggers []interface{} `json:"stop_triggers"`
  TimeboxMinutes int64 `json:"timebox_minutes"`
}

func (strct *AcceptanceCriteria) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "Baseline" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "baseline" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"baseline\": ")
	if tmp, err := json.Marshal(strct.Baseline); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "Effective" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "effective" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"effective\": ")
	if tmp, err := json.Marshal(strct.Effective); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *AcceptanceCriteria) UnmarshalJSON(b []byte) error {
    baselineReceived := false
    effectiveReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "baseline":
            if err := json.Unmarshal([]byte(v), &strct.Baseline); err != nil {
                return err
             }
            baselineReceived = true
        case "effective":
            if err := json.Unmarshal([]byte(v), &strct.Effective); err != nil {
                return err
             }
            effectiveReceived = true
        }
    }
    // check if baseline (a required property) was received
    if !baselineReceived {
        return errors.New("\"baseline\" is required but was not present")
    }
    // check if effective (a required property) was received
    if !effectiveReceived {
        return errors.New("\"effective\" is required but was not present")
    }
    return nil
}

func (strct *Plan) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "AcceptanceCriteria" field is required
    if strct.AcceptanceCriteria == nil {
        return nil, errors.New("acceptance_criteria is a required field")
    }
    // Marshal the "acceptance_criteria" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"acceptance_criteria\": ")
	if tmp, err := json.Marshal(strct.AcceptanceCriteria); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "constraints" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"constraints\": ")
	if tmp, err := json.Marshal(strct.Constraints); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "Goal" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "goal" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"goal\": ")
	if tmp, err := json.Marshal(strct.Goal); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "TaskId" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "task_id" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"task_id\": ")
	if tmp, err := json.Marshal(strct.TaskId); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "WorkPlan" field is required
    if strct.WorkPlan == nil {
        return nil, errors.New("work_plan is a required field")
    }
    // Marshal the "work_plan" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"work_plan\": ")
	if tmp, err := json.Marshal(strct.WorkPlan); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Plan) UnmarshalJSON(b []byte) error {
    acceptance_criteriaReceived := false
    goalReceived := false
    task_idReceived := false
    work_planReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "acceptance_criteria":
            if err := json.Unmarshal([]byte(v), &strct.AcceptanceCriteria); err != nil {
                return err
             }
            acceptance_criteriaReceived = true
        case "constraints":
            if err := json.Unmarshal([]byte(v), &strct.Constraints); err != nil {
                return err
             }
        case "goal":
            if err := json.Unmarshal([]byte(v), &strct.Goal); err != nil {
                return err
             }
            goalReceived = true
        case "task_id":
            if err := json.Unmarshal([]byte(v), &strct.TaskId); err != nil {
                return err
             }
            task_idReceived = true
        case "work_plan":
            if err := json.Unmarshal([]byte(v), &strct.WorkPlan); err != nil {
                return err
             }
            work_planReceived = true
        }
    }
    // check if acceptance_criteria (a required property) was received
    if !acceptance_criteriaReceived {
        return errors.New("\"acceptance_criteria\" is required but was not present")
    }
    // check if goal (a required property) was received
    if !goalReceived {
        return errors.New("\"goal\" is required but was not present")
    }
    // check if task_id (a required property) was received
    if !task_idReceived {
        return errors.New("\"task_id\" is required but was not present")
    }
    // check if work_plan (a required property) was received
    if !work_planReceived {
        return errors.New("\"work_plan\" is required but was not present")
    }
    return nil
}

func (strct *Progress) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "Details" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "details" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"details\": ")
	if tmp, err := json.Marshal(strct.Details); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "Title" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "title" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"title\": ")
	if tmp, err := json.Marshal(strct.Title); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Progress) UnmarshalJSON(b []byte) error {
    detailsReceived := false
    titleReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "details":
            if err := json.Unmarshal([]byte(v), &strct.Details); err != nil {
                return err
             }
            detailsReceived = true
        case "title":
            if err := json.Unmarshal([]byte(v), &strct.Title); err != nil {
                return err
             }
            titleReceived = true
        }
    }
    // check if details (a required property) was received
    if !detailsReceived {
        return errors.New("\"details\" is required but was not present")
    }
    // check if title (a required property) was received
    if !titleReceived {
        return errors.New("\"title\" is required but was not present")
    }
    return nil
}

func (strct *Root) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "Plan" field is required
    if strct.Plan == nil {
        return nil, errors.New("plan is a required field")
    }
    // Marshal the "plan" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"plan\": ")
	if tmp, err := json.Marshal(strct.Plan); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "Progress" field is required
    if strct.Progress == nil {
        return nil, errors.New("progress is a required field")
    }
    // Marshal the "progress" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"progress\": ")
	if tmp, err := json.Marshal(strct.Progress); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "Status" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "status" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"status\": ")
	if tmp, err := json.Marshal(strct.Status); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "stop_reason" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"stop_reason\": ")
	if tmp, err := json.Marshal(strct.StopReason); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "Summary" field is required
    if strct.Summary == nil {
        return nil, errors.New("summary is a required field")
    }
    // Marshal the "summary" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"summary\": ")
	if tmp, err := json.Marshal(strct.Summary); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Root) UnmarshalJSON(b []byte) error {
    planReceived := false
    progressReceived := false
    statusReceived := false
    summaryReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "plan":
            if err := json.Unmarshal([]byte(v), &strct.Plan); err != nil {
                return err
             }
            planReceived = true
        case "progress":
            if err := json.Unmarshal([]byte(v), &strct.Progress); err != nil {
                return err
             }
            progressReceived = true
        case "status":
            if err := json.Unmarshal([]byte(v), &strct.Status); err != nil {
                return err
             }
            statusReceived = true
        case "stop_reason":
            if err := json.Unmarshal([]byte(v), &strct.StopReason); err != nil {
                return err
             }
        case "summary":
            if err := json.Unmarshal([]byte(v), &strct.Summary); err != nil {
                return err
             }
            summaryReceived = true
        }
    }
    // check if plan (a required property) was received
    if !planReceived {
        return errors.New("\"plan\" is required but was not present")
    }
    // check if progress (a required property) was received
    if !progressReceived {
        return errors.New("\"progress\" is required but was not present")
    }
    // check if status (a required property) was received
    if !statusReceived {
        return errors.New("\"status\" is required but was not present")
    }
    // check if summary (a required property) was received
    if !summaryReceived {
        return errors.New("\"summary\" is required but was not present")
    }
    return nil
}

func (strct *Summary) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "Text" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "text" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"text\": ")
	if tmp, err := json.Marshal(strct.Text); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Summary) UnmarshalJSON(b []byte) error {
    textReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "text":
            if err := json.Unmarshal([]byte(v), &strct.Text); err != nil {
                return err
             }
            textReceived = true
        }
    }
    // check if text (a required property) was received
    if !textReceived {
        return errors.New("\"text\" is required but was not present")
    }
    return nil
}

func (strct *WorkPlan) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "CheckSteps" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "check_steps" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"check_steps\": ")
	if tmp, err := json.Marshal(strct.CheckSteps); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "DoSteps" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "do_steps" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"do_steps\": ")
	if tmp, err := json.Marshal(strct.DoSteps); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "StopTriggers" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "stop_triggers" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"stop_triggers\": ")
	if tmp, err := json.Marshal(strct.StopTriggers); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "TimeboxMinutes" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "timebox_minutes" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"timebox_minutes\": ")
	if tmp, err := json.Marshal(strct.TimeboxMinutes); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *WorkPlan) UnmarshalJSON(b []byte) error {
    check_stepsReceived := false
    do_stepsReceived := false
    stop_triggersReceived := false
    timebox_minutesReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "check_steps":
            if err := json.Unmarshal([]byte(v), &strct.CheckSteps); err != nil {
                return err
             }
            check_stepsReceived = true
        case "do_steps":
            if err := json.Unmarshal([]byte(v), &strct.DoSteps); err != nil {
                return err
             }
            do_stepsReceived = true
        case "stop_triggers":
            if err := json.Unmarshal([]byte(v), &strct.StopTriggers); err != nil {
                return err
             }
            stop_triggersReceived = true
        case "timebox_minutes":
            if err := json.Unmarshal([]byte(v), &strct.TimeboxMinutes); err != nil {
                return err
             }
            timebox_minutesReceived = true
        }
    }
    // check if check_steps (a required property) was received
    if !check_stepsReceived {
        return errors.New("\"check_steps\" is required but was not present")
    }
    // check if do_steps (a required property) was received
    if !do_stepsReceived {
        return errors.New("\"do_steps\" is required but was not present")
    }
    // check if stop_triggers (a required property) was received
    if !stop_triggersReceived {
        return errors.New("\"stop_triggers\" is required but was not present")
    }
    // check if timebox_minutes (a required property) was received
    if !timebox_minutesReceived {
        return errors.New("\"timebox_minutes\" is required but was not present")
    }
    return nil
}
