// Code generated by schema-generate. DO NOT EDIT.

package check

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
)

// AcceptanceCriterion
type AcceptanceCriterion struct {
	Checks []Check `json:"checks"`
	Id     string  `json:"id"`
	Text   string  `json:"text"`
}

// Check
type Check struct {
	Command           string  `json:"command"`
	ExpectedExitCodes []int64 `json:"expected_exit_codes"`
	Id                string  `json:"id"`
}

// CheckInput
type CheckInput struct {
	AcceptanceCriteria []AcceptanceCriterion `json:"acceptance_criteria"`
	DoSteps            []DoStep              `json:"do_steps"`
	ExecutedStepIds    []string              `json:"executed_step_ids"`
}

// CheckRequest
type CheckRequest struct {
	CheckInput *CheckInput `json:"check_input"`
	Paths      *Paths      `json:"paths"`
	Run        *Run        `json:"run"`
	Step       *Step       `json:"step"`
	Task       *Task       `json:"task"`
}

// DoStep
type DoStep struct {
	Id   string `json:"id"`
	Text string `json:"text"`
}

// Paths
type Paths struct {
	WorkspaceDir string `json:"workspace_dir"`
}

// Run
type Run struct {
	Id        string `json:"id"`
	Iteration int64  `json:"iteration"`
}

// Step
type Step struct {
	Index int64 `json:"index"`
}

// Task
type Task struct {
	Goal string `json:"goal"`
	Id   string `json:"id"`
}

func (strct *AcceptanceCriterion) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
	comma := false
	// "Checks" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "checks" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"checks\": ")
	if tmp, err := json.Marshal(strct.Checks); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Id" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "id" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"id\": ")
	if tmp, err := json.Marshal(strct.Id); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Text" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "text" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"text\": ")
	if tmp, err := json.Marshal(strct.Text); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *AcceptanceCriterion) UnmarshalJSON(b []byte) error {
	checksReceived := false
	idReceived := false
	textReceived := false
	var jsonMap map[string]json.RawMessage
	if err := json.Unmarshal(b, &jsonMap); err != nil {
		return err
	}
	// parse all the defined properties
	for k, v := range jsonMap {
		switch k {
		case "checks":
			if err := json.Unmarshal([]byte(v), &strct.Checks); err != nil {
				return err
			}
			checksReceived = true
		case "id":
			if err := json.Unmarshal([]byte(v), &strct.Id); err != nil {
				return err
			}
			idReceived = true
		case "text":
			if err := json.Unmarshal([]byte(v), &strct.Text); err != nil {
				return err
			}
			textReceived = true
		default:
			return fmt.Errorf("additional property not allowed: %q", k)
		}
	}
	// check if checks (a required property) was received
	if !checksReceived {
		return errors.New("\"checks\" is required but was not present")
	}
	// check if id (a required property) was received
	if !idReceived {
		return errors.New("\"id\" is required but was not present")
	}
	// check if text (a required property) was received
	if !textReceived {
		return errors.New("\"text\" is required but was not present")
	}
	return nil
}

func (strct *Check) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
	comma := false
	// "Command" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "command" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"command\": ")
	if tmp, err := json.Marshal(strct.Command); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "ExpectedExitCodes" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "expected_exit_codes" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"expected_exit_codes\": ")
	if tmp, err := json.Marshal(strct.ExpectedExitCodes); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Id" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "id" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"id\": ")
	if tmp, err := json.Marshal(strct.Id); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Check) UnmarshalJSON(b []byte) error {
	commandReceived := false
	expected_exit_codesReceived := false
	idReceived := false
	var jsonMap map[string]json.RawMessage
	if err := json.Unmarshal(b, &jsonMap); err != nil {
		return err
	}
	// parse all the defined properties
	for k, v := range jsonMap {
		switch k {
		case "command":
			if err := json.Unmarshal([]byte(v), &strct.Command); err != nil {
				return err
			}
			commandReceived = true
		case "expected_exit_codes":
			if err := json.Unmarshal([]byte(v), &strct.ExpectedExitCodes); err != nil {
				return err
			}
			expected_exit_codesReceived = true
		case "id":
			if err := json.Unmarshal([]byte(v), &strct.Id); err != nil {
				return err
			}
			idReceived = true
		default:
			return fmt.Errorf("additional property not allowed: %q", k)
		}
	}
	// check if command (a required property) was received
	if !commandReceived {
		return errors.New("\"command\" is required but was not present")
	}
	// check if expected_exit_codes (a required property) was received
	if !expected_exit_codesReceived {
		return errors.New("\"expected_exit_codes\" is required but was not present")
	}
	// check if id (a required property) was received
	if !idReceived {
		return errors.New("\"id\" is required but was not present")
	}
	return nil
}

func (strct *CheckInput) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
	comma := false
	// "AcceptanceCriteria" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "acceptance_criteria" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"acceptance_criteria\": ")
	if tmp, err := json.Marshal(strct.AcceptanceCriteria); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "DoSteps" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "do_steps" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"do_steps\": ")
	if tmp, err := json.Marshal(strct.DoSteps); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "ExecutedStepIds" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "executed_step_ids" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"executed_step_ids\": ")
	if tmp, err := json.Marshal(strct.ExecutedStepIds); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *CheckInput) UnmarshalJSON(b []byte) error {
	acceptance_criteriaReceived := false
	do_stepsReceived := false
	executed_step_idsReceived := false
	var jsonMap map[string]json.RawMessage
	if err := json.Unmarshal(b, &jsonMap); err != nil {
		return err
	}
	// parse all the defined properties
	for k, v := range jsonMap {
		switch k {
		case "acceptance_criteria":
			if err := json.Unmarshal([]byte(v), &strct.AcceptanceCriteria); err != nil {
				return err
			}
			acceptance_criteriaReceived = true
		case "do_steps":
			if err := json.Unmarshal([]byte(v), &strct.DoSteps); err != nil {
				return err
			}
			do_stepsReceived = true
		case "executed_step_ids":
			if err := json.Unmarshal([]byte(v), &strct.ExecutedStepIds); err != nil {
				return err
			}
			executed_step_idsReceived = true
		default:
			return fmt.Errorf("additional property not allowed: %q", k)
		}
	}
	// check if acceptance_criteria (a required property) was received
	if !acceptance_criteriaReceived {
		return errors.New("\"acceptance_criteria\" is required but was not present")
	}
	// check if do_steps (a required property) was received
	if !do_stepsReceived {
		return errors.New("\"do_steps\" is required but was not present")
	}
	// check if executed_step_ids (a required property) was received
	if !executed_step_idsReceived {
		return errors.New("\"executed_step_ids\" is required but was not present")
	}
	return nil
}

func (strct *CheckRequest) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
	comma := false
	// "CheckInput" field is required
	if strct.CheckInput == nil {
		return nil, errors.New("check_input is a required field")
	}
	// Marshal the "check_input" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"check_input\": ")
	if tmp, err := json.Marshal(strct.CheckInput); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Paths" field is required
	if strct.Paths == nil {
		return nil, errors.New("paths is a required field")
	}
	// Marshal the "paths" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"paths\": ")
	if tmp, err := json.Marshal(strct.Paths); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Run" field is required
	if strct.Run == nil {
		return nil, errors.New("run is a required field")
	}
	// Marshal the "run" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"run\": ")
	if tmp, err := json.Marshal(strct.Run); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Step" field is required
	if strct.Step == nil {
		return nil, errors.New("step is a required field")
	}
	// Marshal the "step" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"step\": ")
	if tmp, err := json.Marshal(strct.Step); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Task" field is required
	if strct.Task == nil {
		return nil, errors.New("task is a required field")
	}
	// Marshal the "task" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"task\": ")
	if tmp, err := json.Marshal(strct.Task); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *CheckRequest) UnmarshalJSON(b []byte) error {
	check_inputReceived := false
	pathsReceived := false
	runReceived := false
	stepReceived := false
	taskReceived := false
	var jsonMap map[string]json.RawMessage
	if err := json.Unmarshal(b, &jsonMap); err != nil {
		return err
	}
	// parse all the defined properties
	for k, v := range jsonMap {
		switch k {
		case "check_input":
			if err := json.Unmarshal([]byte(v), &strct.CheckInput); err != nil {
				return err
			}
			check_inputReceived = true
		case "paths":
			if err := json.Unmarshal([]byte(v), &strct.Paths); err != nil {
				return err
			}
			pathsReceived = true
		case "run":
			if err := json.Unmarshal([]byte(v), &strct.Run); err != nil {
				return err
			}
			runReceived = true
		case "step":
			if err := json.Unmarshal([]byte(v), &strct.Step); err != nil {
				return err
			}
			stepReceived = true
		case "task":
			if err := json.Unmarshal([]byte(v), &strct.Task); err != nil {
				return err
			}
			taskReceived = true
		default:
			return fmt.Errorf("additional property not allowed: %q", k)
		}
	}
	// check if check_input (a required property) was received
	if !check_inputReceived {
		return errors.New("\"check_input\" is required but was not present")
	}
	// check if paths (a required property) was received
	if !pathsReceived {
		return errors.New("\"paths\" is required but was not present")
	}
	// check if run (a required property) was received
	if !runReceived {
		return errors.New("\"run\" is required but was not present")
	}
	// check if step (a required property) was received
	if !stepReceived {
		return errors.New("\"step\" is required but was not present")
	}
	// check if task (a required property) was received
	if !taskReceived {
		return errors.New("\"task\" is required but was not present")
	}
	return nil
}

func (strct *DoStep) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
	comma := false
	// "Id" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "id" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"id\": ")
	if tmp, err := json.Marshal(strct.Id); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Text" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "text" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"text\": ")
	if tmp, err := json.Marshal(strct.Text); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *DoStep) UnmarshalJSON(b []byte) error {
	idReceived := false
	textReceived := false
	var jsonMap map[string]json.RawMessage
	if err := json.Unmarshal(b, &jsonMap); err != nil {
		return err
	}
	// parse all the defined properties
	for k, v := range jsonMap {
		switch k {
		case "id":
			if err := json.Unmarshal([]byte(v), &strct.Id); err != nil {
				return err
			}
			idReceived = true
		case "text":
			if err := json.Unmarshal([]byte(v), &strct.Text); err != nil {
				return err
			}
			textReceived = true
		default:
			return fmt.Errorf("additional property not allowed: %q", k)
		}
	}
	// check if id (a required property) was received
	if !idReceived {
		return errors.New("\"id\" is required but was not present")
	}
	// check if text (a required property) was received
	if !textReceived {
		return errors.New("\"text\" is required but was not present")
	}
	return nil
}

func (strct *Paths) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
	comma := false
	// "WorkspaceDir" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "workspace_dir" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"workspace_dir\": ")
	if tmp, err := json.Marshal(strct.WorkspaceDir); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Paths) UnmarshalJSON(b []byte) error {
	workspace_dirReceived := false
	var jsonMap map[string]json.RawMessage
	if err := json.Unmarshal(b, &jsonMap); err != nil {
		return err
	}
	// parse all the defined properties
	for k, v := range jsonMap {
		switch k {
		case "workspace_dir":
			if err := json.Unmarshal([]byte(v), &strct.WorkspaceDir); err != nil {
				return err
			}
			workspace_dirReceived = true
		default:
			return fmt.Errorf("additional property not allowed: %q", k)
		}
	}
	// check if workspace_dir (a required property) was received
	if !workspace_dirReceived {
		return errors.New("\"workspace_dir\" is required but was not present")
	}
	return nil
}

func (strct *Run) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
	comma := false
	// "Id" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "id" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"id\": ")
	if tmp, err := json.Marshal(strct.Id); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Iteration" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "iteration" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"iteration\": ")
	if tmp, err := json.Marshal(strct.Iteration); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Run) UnmarshalJSON(b []byte) error {
	idReceived := false
	iterationReceived := false
	var jsonMap map[string]json.RawMessage
	if err := json.Unmarshal(b, &jsonMap); err != nil {
		return err
	}
	// parse all the defined properties
	for k, v := range jsonMap {
		switch k {
		case "id":
			if err := json.Unmarshal([]byte(v), &strct.Id); err != nil {
				return err
			}
			idReceived = true
		case "iteration":
			if err := json.Unmarshal([]byte(v), &strct.Iteration); err != nil {
				return err
			}
			iterationReceived = true
		default:
			return fmt.Errorf("additional property not allowed: %q", k)
		}
	}
	// check if id (a required property) was received
	if !idReceived {
		return errors.New("\"id\" is required but was not present")
	}
	// check if iteration (a required property) was received
	if !iterationReceived {
		return errors.New("\"iteration\" is required but was not present")
	}
	return nil
}

func (strct *Step) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
	comma := false
	// "Index" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "index" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"index\": ")
	if tmp, err := json.Marshal(strct.Index); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Step) UnmarshalJSON(b []byte) error {
	indexReceived := false
	var jsonMap map[string]json.RawMessage
	if err := json.Unmarshal(b, &jsonMap); err != nil {
		return err
	}
	// parse all the defined properties
	for k, v := range jsonMap {
		switch k {
		case "index":
			if err := json.Unmarshal([]byte(v), &strct.Index); err != nil {
				return err
			}
			indexReceived = true
		default:
			return fmt.Errorf("additional property not allowed: %q", k)
		}
	}
	// check if index (a required property) was received
	if !indexReceived {
		return errors.New("\"index\" is required but was not present")
	}
	return nil
}

func (strct *Task) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
	comma := false
	// "Goal" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "goal" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"goal\": ")
	if tmp, err := json.Marshal(strct.Goal); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Id" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "id" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"id\": ")
	if tmp, err := json.Marshal(strct.Id); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Task) UnmarshalJSON(b []byte) error {
	goalReceived := false
	idReceived := false
	var jsonMap map[string]json.RawMessage
	if err := json.Unmarshal(b, &jsonMap); err != nil {
		return err
	}
	// parse all the defined properties
	for k, v := range jsonMap {
		switch k {
		case "goal":
			if err := json.Unmarshal([]byte(v), &strct.Goal); err != nil {
				return err
			}
			goalReceived = true
		case "id":
			if err := json.Unmarshal([]byte(v), &strct.Id); err != nil {
				return err
			}
			idReceived = true
		default:
			return fmt.Errorf("additional property not allowed: %q", k)
		}
	}
	// check if goal (a required property) was received
	if !goalReceived {
		return errors.New("\"goal\" is required but was not present")
	}
	// check if id (a required property) was received
	if !idReceived {
		return errors.New("\"id\" is required but was not present")
	}
	return nil
}
