// Code generated by schema-generate. DO NOT EDIT.

package check

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
)

// AcceptanceResult
type AcceptanceResult struct {
	AcId   string `json:"ac_id"`
	Notes  string `json:"notes"`
	Result string `json:"result"`
}

// CheckOutput
type CheckOutput struct {
	AcceptanceResults []AcceptanceResult `json:"acceptance_results"`
	Verdict           string             `json:"verdict"`
}

// CheckResponse
type CheckResponse struct {
	CheckOutput *CheckOutput `json:"check_output"`
	Status      string       `json:"status"`
	StopReason  string       `json:"stop_reason,omitempty"`
	Summary     string       `json:"summary"`
}

func (strct *AcceptanceResult) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
	comma := false
	// "AcId" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "ac_id" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"ac_id\": ")
	if tmp, err := json.Marshal(strct.AcId); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Notes" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "notes" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"notes\": ")
	if tmp, err := json.Marshal(strct.Notes); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Result" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "result" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"result\": ")
	if tmp, err := json.Marshal(strct.Result); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *AcceptanceResult) UnmarshalJSON(b []byte) error {
	ac_idReceived := false
	notesReceived := false
	resultReceived := false
	var jsonMap map[string]json.RawMessage
	if err := json.Unmarshal(b, &jsonMap); err != nil {
		return err
	}
	// parse all the defined properties
	for k, v := range jsonMap {
		switch k {
		case "ac_id":
			if err := json.Unmarshal([]byte(v), &strct.AcId); err != nil {
				return err
			}
			ac_idReceived = true
		case "notes":
			if err := json.Unmarshal([]byte(v), &strct.Notes); err != nil {
				return err
			}
			notesReceived = true
		case "result":
			if err := json.Unmarshal([]byte(v), &strct.Result); err != nil {
				return err
			}
			resultReceived = true
		default:
			return fmt.Errorf("additional property not allowed: %q", k)
		}
	}
	// check if ac_id (a required property) was received
	if !ac_idReceived {
		return errors.New("\"ac_id\" is required but was not present")
	}
	// check if notes (a required property) was received
	if !notesReceived {
		return errors.New("\"notes\" is required but was not present")
	}
	// check if result (a required property) was received
	if !resultReceived {
		return errors.New("\"result\" is required but was not present")
	}
	return nil
}

func (strct *CheckOutput) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
	comma := false
	// "AcceptanceResults" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "acceptance_results" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"acceptance_results\": ")
	if tmp, err := json.Marshal(strct.AcceptanceResults); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Verdict" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "verdict" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"verdict\": ")
	if tmp, err := json.Marshal(strct.Verdict); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *CheckOutput) UnmarshalJSON(b []byte) error {
	acceptance_resultsReceived := false
	verdictReceived := false
	var jsonMap map[string]json.RawMessage
	if err := json.Unmarshal(b, &jsonMap); err != nil {
		return err
	}
	// parse all the defined properties
	for k, v := range jsonMap {
		switch k {
		case "acceptance_results":
			if err := json.Unmarshal([]byte(v), &strct.AcceptanceResults); err != nil {
				return err
			}
			acceptance_resultsReceived = true
		case "verdict":
			if err := json.Unmarshal([]byte(v), &strct.Verdict); err != nil {
				return err
			}
			verdictReceived = true
		default:
			return fmt.Errorf("additional property not allowed: %q", k)
		}
	}
	// check if acceptance_results (a required property) was received
	if !acceptance_resultsReceived {
		return errors.New("\"acceptance_results\" is required but was not present")
	}
	// check if verdict (a required property) was received
	if !verdictReceived {
		return errors.New("\"verdict\" is required but was not present")
	}
	return nil
}

func (strct *CheckResponse) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
	comma := false
	// "CheckOutput" field is required
	if strct.CheckOutput == nil {
		return nil, errors.New("check_output is a required field")
	}
	// Marshal the "check_output" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"check_output\": ")
	if tmp, err := json.Marshal(strct.CheckOutput); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Status" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "status" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"status\": ")
	if tmp, err := json.Marshal(strct.Status); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// Marshal the "stop_reason" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"stop_reason\": ")
	if tmp, err := json.Marshal(strct.StopReason); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true
	// "Summary" field is required
	// only required object types supported for marshal checking (for now)
	// Marshal the "summary" field
	if comma {
		buf.WriteString(",")
	}
	buf.WriteString("\"summary\": ")
	if tmp, err := json.Marshal(strct.Summary); err != nil {
		return nil, err
	} else {
		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *CheckResponse) UnmarshalJSON(b []byte) error {
	check_outputReceived := false
	statusReceived := false
	summaryReceived := false
	var jsonMap map[string]json.RawMessage
	if err := json.Unmarshal(b, &jsonMap); err != nil {
		return err
	}
	// parse all the defined properties
	for k, v := range jsonMap {
		switch k {
		case "check_output":
			if err := json.Unmarshal([]byte(v), &strct.CheckOutput); err != nil {
				return err
			}
			check_outputReceived = true
		case "status":
			if err := json.Unmarshal([]byte(v), &strct.Status); err != nil {
				return err
			}
			statusReceived = true
		case "stop_reason":
			if err := json.Unmarshal([]byte(v), &strct.StopReason); err != nil {
				return err
			}
		case "summary":
			if err := json.Unmarshal([]byte(v), &strct.Summary); err != nil {
				return err
			}
			summaryReceived = true
		default:
			return fmt.Errorf("additional property not allowed: %q", k)
		}
	}
	// check if check_output (a required property) was received
	if !check_outputReceived {
		return errors.New("\"check_output\" is required but was not present")
	}
	// check if status (a required property) was received
	if !statusReceived {
		return errors.New("\"status\" is required but was not present")
	}
	// check if summary (a required property) was received
	if !summaryReceived {
		return errors.New("\"summary\" is required but was not present")
	}
	return nil
}
