// Code generated by schema-generate. DO NOT EDIT.

package do

import (
    "bytes"
    "errors"
    "encoding/json"
)

// Do 
type Do struct {
  Blockers []interface{} `json:"blockers,omitempty"`
  Execution *Execution `json:"execution"`
}

// Execution 
type Execution struct {
  Commands []interface{} `json:"commands"`
  ExecutedStepIds []string `json:"executed_step_ids"`
  SkippedStepIds []string `json:"skipped_step_ids"`
}

// Progress 
type Progress struct {
  Details []string `json:"details"`
  Title string `json:"title"`
}

// Root 
type Root struct {
  Do *Do `json:"do"`
  Progress *Progress `json:"progress"`
  Status string `json:"status"`
  StopReason string `json:"stop_reason,omitempty"`
  Summary *Summary `json:"summary"`
}

// Summary 
type Summary struct {
  Text string `json:"text"`
}

func (strct *Do) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // Marshal the "blockers" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"blockers\": ")
	if tmp, err := json.Marshal(strct.Blockers); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "Execution" field is required
    if strct.Execution == nil {
        return nil, errors.New("execution is a required field")
    }
    // Marshal the "execution" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"execution\": ")
	if tmp, err := json.Marshal(strct.Execution); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Do) UnmarshalJSON(b []byte) error {
    executionReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "blockers":
            if err := json.Unmarshal([]byte(v), &strct.Blockers); err != nil {
                return err
             }
        case "execution":
            if err := json.Unmarshal([]byte(v), &strct.Execution); err != nil {
                return err
             }
            executionReceived = true
        }
    }
    // check if execution (a required property) was received
    if !executionReceived {
        return errors.New("\"execution\" is required but was not present")
    }
    return nil
}

func (strct *Execution) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "Commands" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "commands" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"commands\": ")
	if tmp, err := json.Marshal(strct.Commands); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "ExecutedStepIds" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "executed_step_ids" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"executed_step_ids\": ")
	if tmp, err := json.Marshal(strct.ExecutedStepIds); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "SkippedStepIds" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "skipped_step_ids" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"skipped_step_ids\": ")
	if tmp, err := json.Marshal(strct.SkippedStepIds); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Execution) UnmarshalJSON(b []byte) error {
    commandsReceived := false
    executed_step_idsReceived := false
    skipped_step_idsReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "commands":
            if err := json.Unmarshal([]byte(v), &strct.Commands); err != nil {
                return err
             }
            commandsReceived = true
        case "executed_step_ids":
            if err := json.Unmarshal([]byte(v), &strct.ExecutedStepIds); err != nil {
                return err
             }
            executed_step_idsReceived = true
        case "skipped_step_ids":
            if err := json.Unmarshal([]byte(v), &strct.SkippedStepIds); err != nil {
                return err
             }
            skipped_step_idsReceived = true
        }
    }
    // check if commands (a required property) was received
    if !commandsReceived {
        return errors.New("\"commands\" is required but was not present")
    }
    // check if executed_step_ids (a required property) was received
    if !executed_step_idsReceived {
        return errors.New("\"executed_step_ids\" is required but was not present")
    }
    // check if skipped_step_ids (a required property) was received
    if !skipped_step_idsReceived {
        return errors.New("\"skipped_step_ids\" is required but was not present")
    }
    return nil
}

func (strct *Progress) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "Details" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "details" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"details\": ")
	if tmp, err := json.Marshal(strct.Details); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "Title" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "title" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"title\": ")
	if tmp, err := json.Marshal(strct.Title); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Progress) UnmarshalJSON(b []byte) error {
    detailsReceived := false
    titleReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "details":
            if err := json.Unmarshal([]byte(v), &strct.Details); err != nil {
                return err
             }
            detailsReceived = true
        case "title":
            if err := json.Unmarshal([]byte(v), &strct.Title); err != nil {
                return err
             }
            titleReceived = true
        }
    }
    // check if details (a required property) was received
    if !detailsReceived {
        return errors.New("\"details\" is required but was not present")
    }
    // check if title (a required property) was received
    if !titleReceived {
        return errors.New("\"title\" is required but was not present")
    }
    return nil
}

func (strct *Root) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "Do" field is required
    if strct.Do == nil {
        return nil, errors.New("do is a required field")
    }
    // Marshal the "do" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"do\": ")
	if tmp, err := json.Marshal(strct.Do); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "Progress" field is required
    if strct.Progress == nil {
        return nil, errors.New("progress is a required field")
    }
    // Marshal the "progress" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"progress\": ")
	if tmp, err := json.Marshal(strct.Progress); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "Status" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "status" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"status\": ")
	if tmp, err := json.Marshal(strct.Status); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "stop_reason" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"stop_reason\": ")
	if tmp, err := json.Marshal(strct.StopReason); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "Summary" field is required
    if strct.Summary == nil {
        return nil, errors.New("summary is a required field")
    }
    // Marshal the "summary" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"summary\": ")
	if tmp, err := json.Marshal(strct.Summary); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Root) UnmarshalJSON(b []byte) error {
    doReceived := false
    progressReceived := false
    statusReceived := false
    summaryReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "do":
            if err := json.Unmarshal([]byte(v), &strct.Do); err != nil {
                return err
             }
            doReceived = true
        case "progress":
            if err := json.Unmarshal([]byte(v), &strct.Progress); err != nil {
                return err
             }
            progressReceived = true
        case "status":
            if err := json.Unmarshal([]byte(v), &strct.Status); err != nil {
                return err
             }
            statusReceived = true
        case "stop_reason":
            if err := json.Unmarshal([]byte(v), &strct.StopReason); err != nil {
                return err
             }
        case "summary":
            if err := json.Unmarshal([]byte(v), &strct.Summary); err != nil {
                return err
             }
            summaryReceived = true
        }
    }
    // check if do (a required property) was received
    if !doReceived {
        return errors.New("\"do\" is required but was not present")
    }
    // check if progress (a required property) was received
    if !progressReceived {
        return errors.New("\"progress\" is required but was not present")
    }
    // check if status (a required property) was received
    if !statusReceived {
        return errors.New("\"status\" is required but was not present")
    }
    // check if summary (a required property) was received
    if !summaryReceived {
        return errors.New("\"summary\" is required but was not present")
    }
    return nil
}

func (strct *Summary) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "Text" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "text" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"text\": ")
	if tmp, err := json.Marshal(strct.Text); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Summary) UnmarshalJSON(b []byte) error {
    textReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "text":
            if err := json.Unmarshal([]byte(v), &strct.Text); err != nil {
                return err
             }
            textReceived = true
        }
    }
    // check if text (a required property) was received
    if !textReceived {
        return errors.New("\"text\" is required but was not present")
    }
    return nil
}
