// Code generated by options-gen v0.55.5. DO NOT EDIT.

package goalkeeper

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
	"google.golang.org/adk/agent"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	worker agent.Agent,
	validator agent.Agent,
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	o.worker = worker
	o.validator = validator

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("worker", _validate_Options_worker(o)))
	errs.Add(errors461e464ebed9.NewValidationError("validator", _validate_Options_validator(o)))
	return errs.AsError()
}

func _validate_Options_worker(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.worker, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `worker` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_validator(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.validator, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `validator` did not pass the test: %w", err)
	}
	return nil
}
