// Code generated by schema-generate. DO NOT EDIT.

package act

import (
    "bytes"
    "encoding/json"
    "errors"
)

// Act 
type Act struct {
  Decision string `json:"decision"`
  Next *Next `json:"next,omitempty"`
  Rationale string `json:"rationale"`
}

// Next 
type Next struct {
}

// Progress 
type Progress struct {
  Details []string `json:"details"`
  Title string `json:"title"`
}

// Root 
type Root struct {
  Act *Act `json:"act"`
  Progress *Progress `json:"progress"`
  Status string `json:"status"`
  StopReason string `json:"stop_reason,omitempty"`
  Summary *Summary `json:"summary"`
}

// Summary 
type Summary struct {
  Text string `json:"text"`
}

func (strct *Act) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "Decision" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "decision" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"decision\": ")
	if tmp, err := json.Marshal(strct.Decision); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "next" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"next\": ")
	if tmp, err := json.Marshal(strct.Next); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "Rationale" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "rationale" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"rationale\": ")
	if tmp, err := json.Marshal(strct.Rationale); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Act) UnmarshalJSON(b []byte) error {
    decisionReceived := false
    rationaleReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "decision":
            if err := json.Unmarshal([]byte(v), &strct.Decision); err != nil {
                return err
             }
            decisionReceived = true
        case "next":
            if err := json.Unmarshal([]byte(v), &strct.Next); err != nil {
                return err
             }
        case "rationale":
            if err := json.Unmarshal([]byte(v), &strct.Rationale); err != nil {
                return err
             }
            rationaleReceived = true
        }
    }
    // check if decision (a required property) was received
    if !decisionReceived {
        return errors.New("\"decision\" is required but was not present")
    }
    // check if rationale (a required property) was received
    if !rationaleReceived {
        return errors.New("\"rationale\" is required but was not present")
    }
    return nil
}

func (strct *Progress) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "Details" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "details" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"details\": ")
	if tmp, err := json.Marshal(strct.Details); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "Title" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "title" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"title\": ")
	if tmp, err := json.Marshal(strct.Title); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Progress) UnmarshalJSON(b []byte) error {
    detailsReceived := false
    titleReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "details":
            if err := json.Unmarshal([]byte(v), &strct.Details); err != nil {
                return err
             }
            detailsReceived = true
        case "title":
            if err := json.Unmarshal([]byte(v), &strct.Title); err != nil {
                return err
             }
            titleReceived = true
        }
    }
    // check if details (a required property) was received
    if !detailsReceived {
        return errors.New("\"details\" is required but was not present")
    }
    // check if title (a required property) was received
    if !titleReceived {
        return errors.New("\"title\" is required but was not present")
    }
    return nil
}

func (strct *Root) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "Act" field is required
    if strct.Act == nil {
        return nil, errors.New("act is a required field")
    }
    // Marshal the "act" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"act\": ")
	if tmp, err := json.Marshal(strct.Act); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "Progress" field is required
    if strct.Progress == nil {
        return nil, errors.New("progress is a required field")
    }
    // Marshal the "progress" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"progress\": ")
	if tmp, err := json.Marshal(strct.Progress); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "Status" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "status" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"status\": ")
	if tmp, err := json.Marshal(strct.Status); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // Marshal the "stop_reason" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"stop_reason\": ")
	if tmp, err := json.Marshal(strct.StopReason); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true
    // "Summary" field is required
    if strct.Summary == nil {
        return nil, errors.New("summary is a required field")
    }
    // Marshal the "summary" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"summary\": ")
	if tmp, err := json.Marshal(strct.Summary); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Root) UnmarshalJSON(b []byte) error {
    actReceived := false
    progressReceived := false
    statusReceived := false
    summaryReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "act":
            if err := json.Unmarshal([]byte(v), &strct.Act); err != nil {
                return err
             }
            actReceived = true
        case "progress":
            if err := json.Unmarshal([]byte(v), &strct.Progress); err != nil {
                return err
             }
            progressReceived = true
        case "status":
            if err := json.Unmarshal([]byte(v), &strct.Status); err != nil {
                return err
             }
            statusReceived = true
        case "stop_reason":
            if err := json.Unmarshal([]byte(v), &strct.StopReason); err != nil {
                return err
             }
        case "summary":
            if err := json.Unmarshal([]byte(v), &strct.Summary); err != nil {
                return err
             }
            summaryReceived = true
        }
    }
    // check if act (a required property) was received
    if !actReceived {
        return errors.New("\"act\" is required but was not present")
    }
    // check if progress (a required property) was received
    if !progressReceived {
        return errors.New("\"progress\" is required but was not present")
    }
    // check if status (a required property) was received
    if !statusReceived {
        return errors.New("\"status\" is required but was not present")
    }
    // check if summary (a required property) was received
    if !summaryReceived {
        return errors.New("\"summary\" is required but was not present")
    }
    return nil
}

func (strct *Summary) MarshalJSON() ([]byte, error) {
	buf := bytes.NewBuffer(make([]byte, 0))
	buf.WriteString("{")
    comma := false
    // "Text" field is required
    // only required object types supported for marshal checking (for now)
    // Marshal the "text" field
    if comma {
        buf.WriteString(",")
    }
    buf.WriteString("\"text\": ")
	if tmp, err := json.Marshal(strct.Text); err != nil {
		return nil, err
 	} else {
 		buf.Write(tmp)
	}
	comma = true

	buf.WriteString("}")
	rv := buf.Bytes()
	return rv, nil
}

func (strct *Summary) UnmarshalJSON(b []byte) error {
    textReceived := false
    var jsonMap map[string]json.RawMessage
    if err := json.Unmarshal(b, &jsonMap); err != nil {
        return err
    }
    // parse all the defined properties
    for k, v := range jsonMap {
        switch k {
        case "text":
            if err := json.Unmarshal([]byte(v), &strct.Text); err != nil {
                return err
             }
            textReceived = true
        }
    }
    // check if text (a required property) was received
    if !textReceived {
        return errors.New("\"text\" is required but was not present")
    }
    return nil
}
